---
apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web     #to match the web component from client-deployment file
  ports:
    - port: 3000       #port for outside world
      targetPort: 3000
