---
apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:               #as all traffic comes at port 5000 so we define here.
    - port: 5000
      targetPort: 5000
